### PR TITLE
Fixing "AttributeError: 'Popen' object has no attribute 'args'" on Python 2.7 for Linux builds

### PR DESCRIPTION
**Pull request by YannickJadoul**
Silly thing, but Python 2.7's `subprocess.Popen` object does not have an `args` attribute, and so you now get an extra exception instead of a nice overview of the executed command, when the subprocess fails.

### CODE REVIEW

**Comment by YannickJadoul** [comment]
Builds are failing because of #106, but héy, at least the error message is now correct! :-D

```
subprocess.CalledProcessError: Command '['/home/circleci/project/venv/bin/python', '-m', 'cibuildwheel', '/home/circleci/project/test/06_docker_images']' returned non-zero exit status 1
```

**Comment by MuellerSeb** [comment]
Could you provide a release including this, like 0.10.1? At the moment I have to install cibuildwheel with

    $PIP install https://github.com/joerick/cibuildwheel/archive/master.zip

to get everything running.
